### ISSUE TITLE
Max retries exceeded

### ISSUE THREAD

**Issue by xApep** [0x4D-5A/e-scraper#1]
When I run I get and error

`[-] HTTPSConnectionPool(host='%3chttp', port=443): Max retries exceeded with url: //domain.com%3E (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a5615d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) on: https://<domain.com>`

**Comment by 0x4D-5A** [comment]
Looks like you had enter a malformed domain name. 

Can you provide the used domains.txt file for further analysis?
